dump

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -1,10 +1,16 @@
-#!/usr/bin/env bash
-# backup and compress my databases
-
-# variables
-day=$(date +"%d")
-month=$(date +"%m")
-year=$(date +"%Y")
-file_name="$day-$month-$year.tar.gz"
-mysqldump --all-databases -u root --password="$1" > backup.sql
-tar -czvf "$file_name" backup.sql
+#!/bin/bash
+# Check if the correct number of arguments is provided
+if [ "$#" -ne 1 ]; then
+    echo "Usage: $0 <mysql_password>"
+    exit 1
+fi
+# Set the password for MySQL root user
+password=$1
+# Set the date format
+date=$(date +'%d-%m-%Y')
+# Dump all MySQL databases to a backup.sql file
+sudo mysqldump -uroot --password"$password" --all-databases >"backup.sql"
+# Compress the backup.sql file to a tar.gz archive
+tar -czvf "$date.tar.gz" "backup.sql"
+# Clean up the backup.sql file
+rm "backup.sql"
